#!/bin/bash

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT=$(realpath $0)
SCRIPTDIR=$(dirname $SCRIPT)
SCRIPTFILENAME=$(basename $SCRIPT)

LISTFILENAME='list'
LIST=$SCRIPTDIR/$LISTFILENAME

HARDLINKS=0
while getopts "a" opt; do
  case $opt in
    a) HARDLINKS=1;;
  esac
done

case $1 in
  'add')
    ORIGINAL=$(realpath $2)
    TRACKED=$SCRIPTDIR/$ORIGINAL
    TRACKEDDIR=$(dirname $TRACKED)
    if [[ -d $TRACKEDDIR ]]; then
      echo "directory existing"
      exit
    fi
    mkdir -p $TRACKEDDIR
    mv $ORIGINAL $TRACKEDDIR
    ln -s $TRACKED $ORIGINAL
    printf "%q\n" $ORIGINAL >> $LIST
    ;;
  'restore')
    echo 'not implemented'
    ;;
  'push')
    cd $SCRIPTDIR
    git add .
    git commit -am "$(date)"
    git pull
    git push
    ;;
  'pull')
    cd $SCRIPTDIR
    git pull
    ;;
  'install')
    while read ORIGINAL
    do
      TRACKED=$SCRIPTDIR/$ORIGINAL
      ln -s $TRACKED $ORIGINAL
    done < $LIST
    ;;
  *)
    echo "usage: $SCRIPTFILENAME add <source_file>"
    echo "       $SCRIPTFILENAME push|pull|install"
    ;;
esac
