#!/bin/bash

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT=$(realpath $0)
SCRIPTDIR=$(dirname $SCRIPT)

LISTFILENAME='list'
LIST=$SCRIPTDIR/$LISTFILENAME

touch $LIST

case $1 in
  'add')
    ORIGINAL=$(realpath $2)
    TRACKED=$SCRIPTDIR/$ORIGINAL
    TRACKEDDIR=$(dirname $TRACKED)
    if [[ -d $TRACKEDDIR ]]; then
      echo "directory existing"
      exit
    fi
    mkdir --parents $TRACKEDDIR
    mv $ORIGINAL $TRACKEDDIR
    ln --symbolic $TRACKED $ORIGINAL
    printf "%q\n" $ORIGINAL >> $LIST
    ;;
  'restore')
    echo 'not implemented'
    ;;
  'push')
    cd $SCRIPTDIR
    git add .
    git commit -am "$(date)"
    git pull
    git push
    ;;
  'pull')
    cd $SCRIPTDIR
    git pull
    ;;
  'install')
    while read ORIGINAL
    do
      TRACKED=$SCRIPTDIR/$ORIGINAL
      ln --symbolic $TRACKED $ORIGINAL
    done < $LIST
    ;;
  *)
    echo "usage: $0 (add|push|pull|install)"
    ;;
esac
